# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import types_pb2 as types__pb2


class OrderBookManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OrderBook = channel.unary_unary(
        '/OrderBookManager/OrderBook',
        request_serializer=types__pb2.OrderBookRequest.SerializeToString,
        response_deserializer=types__pb2.OrderBookResponse.FromString,
        )


class OrderBookManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OrderBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderBookManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OrderBook': grpc.unary_unary_rpc_method_handler(
          servicer.OrderBook,
          request_deserializer=types__pb2.OrderBookRequest.FromString,
          response_serializer=types__pb2.OrderBookResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OrderBookManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class MakerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetQuote = channel.unary_unary(
        '/Maker/GetQuote',
        request_serializer=types__pb2.GetQuoteRequest.SerializeToString,
        response_deserializer=types__pb2.GetQuoteResponse.FromString,
        )
    self.CheckQuote = channel.unary_unary(
        '/Maker/CheckQuote',
        request_serializer=types__pb2.CheckQuoteRequest.SerializeToString,
        response_deserializer=types__pb2.CheckQuoteResponse.FromString,
        )
    self.OrderStatusUpdate = channel.unary_unary(
        '/Maker/OrderStatusUpdate',
        request_serializer=types__pb2.OrderStatusUpdateRequest.SerializeToString,
        response_deserializer=types__pb2.OrderStatusUpdateResponse.FromString,
        )


class MakerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetQuote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckQuote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OrderStatusUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MakerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetQuote': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuote,
          request_deserializer=types__pb2.GetQuoteRequest.FromString,
          response_serializer=types__pb2.GetQuoteResponse.SerializeToString,
      ),
      'CheckQuote': grpc.unary_unary_rpc_method_handler(
          servicer.CheckQuote,
          request_deserializer=types__pb2.CheckQuoteRequest.FromString,
          response_serializer=types__pb2.CheckQuoteResponse.SerializeToString,
      ),
      'OrderStatusUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.OrderStatusUpdate,
          request_deserializer=types__pb2.OrderStatusUpdateRequest.FromString,
          response_serializer=types__pb2.OrderStatusUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Maker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class HotWalletStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SignOrder = channel.unary_unary(
        '/HotWallet/SignOrder',
        request_serializer=types__pb2.SignOrderRequest.SerializeToString,
        response_deserializer=types__pb2.SignOrderResponse.FromString,
        )
    self.HashOrder = channel.unary_unary(
        '/HotWallet/HashOrder',
        request_serializer=types__pb2.HashOrderRequest.SerializeToString,
        response_deserializer=types__pb2.HashOrderResponse.FromString,
        )
    self.CreateOrder = channel.unary_unary(
        '/HotWallet/CreateOrder',
        request_serializer=types__pb2.CreateOrderRequest.SerializeToString,
        response_deserializer=types__pb2.CreateOrderResponse.FromString,
        )


class HotWalletServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SignOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HashOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HotWalletServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SignOrder': grpc.unary_unary_rpc_method_handler(
          servicer.SignOrder,
          request_deserializer=types__pb2.SignOrderRequest.FromString,
          response_serializer=types__pb2.SignOrderResponse.SerializeToString,
      ),
      'HashOrder': grpc.unary_unary_rpc_method_handler(
          servicer.HashOrder,
          request_deserializer=types__pb2.HashOrderRequest.FromString,
          response_serializer=types__pb2.HashOrderResponse.SerializeToString,
      ),
      'CreateOrder': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOrder,
          request_deserializer=types__pb2.CreateOrderRequest.FromString,
          response_serializer=types__pb2.CreateOrderResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HotWallet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
