# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmaker.proto\"y\n\x0fGetQuoteRequest\x12\x13\n\x0b\x63lientAsset\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65\x61lerAsset\x18\x02 \x01(\t\x12\x12\n\nclientSize\x18\x03 \x01(\t\x12\x12\n\ndealerSize\x18\x04 \x01(\t\x12\x14\n\x0ctakerAddress\x18\x05 \x01(\t\"\x8e\x01\n\rQuoteResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nexpiration\x18\x02 \x01(\t\x12\x13\n\x0b\x63lientAsset\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65\x61lerAsset\x18\x04 \x01(\t\x12\x12\n\nclientSize\x18\x05 \x01(\t\x12\x12\n\ndealerSize\x18\x06 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x07 \x01(\t\"7\n\x11\x43heckQuoteRequest\x12\x0f\n\x07quoteId\x18\x01 \x01(\t\x12\x11\n\torderHash\x18\x02 \x01(\t\"\x13\n\x04\x42ool\x12\x0b\n\x03val\x18\x01 \x01(\t\"B\n\x18OrderStatusUpdateRequest\x12\x11\n\torderHash\x18\x01 \x01(\t\x12\x13\n\x0borderStatus\x18\x02 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t2\x97\x01\n\x05Maker\x12,\n\x08GetQuote\x12\x10.GetQuoteRequest\x1a\x0e.QuoteResponse\x12\'\n\nCheckQuote\x12\x12.CheckQuoteRequest\x1a\x05.Bool\x12\x37\n\x11OrderStatusUpdate\x12\x19.OrderStatusUpdateRequest\x1a\x07.Statusb\x06proto3')
)




_GETQUOTEREQUEST = _descriptor.Descriptor(
  name='GetQuoteRequest',
  full_name='GetQuoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientAsset', full_name='GetQuoteRequest.clientAsset', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dealerAsset', full_name='GetQuoteRequest.dealerAsset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientSize', full_name='GetQuoteRequest.clientSize', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dealerSize', full_name='GetQuoteRequest.dealerSize', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='takerAddress', full_name='GetQuoteRequest.takerAddress', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=136,
)


_QUOTERESPONSE = _descriptor.Descriptor(
  name='QuoteResponse',
  full_name='QuoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='QuoteResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='QuoteResponse.expiration', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientAsset', full_name='QuoteResponse.clientAsset', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dealerAsset', full_name='QuoteResponse.dealerAsset', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientSize', full_name='QuoteResponse.clientSize', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dealerSize', full_name='QuoteResponse.dealerSize', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee', full_name='QuoteResponse.fee', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=281,
)


_CHECKQUOTEREQUEST = _descriptor.Descriptor(
  name='CheckQuoteRequest',
  full_name='CheckQuoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quoteId', full_name='CheckQuoteRequest.quoteId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderHash', full_name='CheckQuoteRequest.orderHash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=338,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Bool.val', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=359,
)


_ORDERSTATUSUPDATEREQUEST = _descriptor.Descriptor(
  name='OrderStatusUpdateRequest',
  full_name='OrderStatusUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderHash', full_name='OrderStatusUpdateRequest.orderHash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderStatus', full_name='OrderStatusUpdateRequest.orderStatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=427,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=453,
)

DESCRIPTOR.message_types_by_name['GetQuoteRequest'] = _GETQUOTEREQUEST
DESCRIPTOR.message_types_by_name['QuoteResponse'] = _QUOTERESPONSE
DESCRIPTOR.message_types_by_name['CheckQuoteRequest'] = _CHECKQUOTEREQUEST
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['OrderStatusUpdateRequest'] = _ORDERSTATUSUPDATEREQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetQuoteRequest = _reflection.GeneratedProtocolMessageType('GetQuoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETQUOTEREQUEST,
  '__module__' : 'maker_pb2'
  # @@protoc_insertion_point(class_scope:GetQuoteRequest)
  })
_sym_db.RegisterMessage(GetQuoteRequest)

QuoteResponse = _reflection.GeneratedProtocolMessageType('QuoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUOTERESPONSE,
  '__module__' : 'maker_pb2'
  # @@protoc_insertion_point(class_scope:QuoteResponse)
  })
_sym_db.RegisterMessage(QuoteResponse)

CheckQuoteRequest = _reflection.GeneratedProtocolMessageType('CheckQuoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKQUOTEREQUEST,
  '__module__' : 'maker_pb2'
  # @@protoc_insertion_point(class_scope:CheckQuoteRequest)
  })
_sym_db.RegisterMessage(CheckQuoteRequest)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'maker_pb2'
  # @@protoc_insertion_point(class_scope:Bool)
  })
_sym_db.RegisterMessage(Bool)

OrderStatusUpdateRequest = _reflection.GeneratedProtocolMessageType('OrderStatusUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSTATUSUPDATEREQUEST,
  '__module__' : 'maker_pb2'
  # @@protoc_insertion_point(class_scope:OrderStatusUpdateRequest)
  })
_sym_db.RegisterMessage(OrderStatusUpdateRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'maker_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)



_MAKER = _descriptor.ServiceDescriptor(
  name='Maker',
  full_name='Maker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=456,
  serialized_end=607,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetQuote',
    full_name='Maker.GetQuote',
    index=0,
    containing_service=None,
    input_type=_GETQUOTEREQUEST,
    output_type=_QUOTERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckQuote',
    full_name='Maker.CheckQuote',
    index=1,
    containing_service=None,
    input_type=_CHECKQUOTEREQUEST,
    output_type=_BOOL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OrderStatusUpdate',
    full_name='Maker.OrderStatusUpdate',
    index=2,
    containing_service=None,
    input_type=_ORDERSTATUSUPDATEREQUEST,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAKER)

DESCRIPTOR.services_by_name['Maker'] = _MAKER

# @@protoc_insertion_point(module_scope)
