# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from services.maker import maker_pb2 as proto_dot_maker__pb2


class MakerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetQuote = channel.unary_unary(
        '/Maker/GetQuote',
        request_serializer=proto_dot_maker__pb2.GetQuoteRequest.SerializeToString,
        response_deserializer=proto_dot_maker__pb2.GetQuoteResponse.FromString,
        )
    self.CheckQuote = channel.unary_unary(
        '/Maker/CheckQuote',
        request_serializer=proto_dot_maker__pb2.CheckQuoteRequest.SerializeToString,
        response_deserializer=proto_dot_maker__pb2.CheckQuoteResponse.FromString,
        )
    self.OrderStatusUpdate = channel.unary_unary(
        '/Maker/OrderStatusUpdate',
        request_serializer=proto_dot_maker__pb2.OrderStatusUpdateRequest.SerializeToString,
        response_deserializer=proto_dot_maker__pb2.OrderStatusUpdateResponse.FromString,
        )


class MakerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetQuote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckQuote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OrderStatusUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MakerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetQuote': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuote,
          request_deserializer=proto_dot_maker__pb2.GetQuoteRequest.FromString,
          response_serializer=proto_dot_maker__pb2.GetQuoteResponse.SerializeToString,
      ),
      'CheckQuote': grpc.unary_unary_rpc_method_handler(
          servicer.CheckQuote,
          request_deserializer=proto_dot_maker__pb2.CheckQuoteRequest.FromString,
          response_serializer=proto_dot_maker__pb2.CheckQuoteResponse.SerializeToString,
      ),
      'OrderStatusUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.OrderStatusUpdate,
          request_deserializer=proto_dot_maker__pb2.OrderStatusUpdateRequest.FromString,
          response_serializer=proto_dot_maker__pb2.OrderStatusUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Maker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
