---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.13
  volumes:
  - name: gocache
    path: /go/pkg/mod
  commands:
    - make test

volumes:
  - name: gocache
    host: 
      path: /tmp/drone/gocache
