---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.13
  volumes:
  - name: gomod
    path: /go/pkg/mod
  - name: gocache
    path: /root/.cache/go-build
  commands:
    - make test

volumes:
  - name: gomod
    host: 
      path: /tmp/drone/zaidan/gomod
  - name: gocache
    host:
      path: /tmp/drone/zaidan/gocache
