---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.13
  volumes:
  - name: gocache
    path: /go/pkg/mod
  commands:
    - make ci
  environment:
    ETHEREUM_JSONRPC_URL: http://0x-snapshot:8545 

services:
- name: 0x-snapshot
  pull: always
  image: gcr.io/zaidan-eth-net/0x-snapshot:v3

volumes:
  - name: gomod
    host: 
      path: /tmp/drone/zaidan/gomod

trigger:
  event:
  - pull_request