---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.13
  volumes:
  - name: gomod
    path: /go/pkg/mod
  - name: gocache
    path: /root/.cache/go-build
  commands:
    - make ci

services:
- name: 0x-snapshot
  pull: always
  image: gcr.io/zaidan-eth-net/0x-snapshot:v3

volumes:
  - name: gomod
    host: 
      path: /tmp/drone/zaidan/gomod
  - name: gocache
    host:
      path: /tmp/drone/zaidan/gocache

trigger:
  event:
  - pull_request
  