# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\004grpc'),
  serialized_pb=_b('\n\x0eservices.proto\x1a\x0btypes.proto2\x81\x01\n\x10OrderBookManager\x12\x32\n\tOrderBook\x12\x11.OrderBookRequest\x1a\x12.OrderBookResponse\x12\x39\n\x07Updates\x12\x18.OrderBookUpdatesRequest\x1a\x12.OrderBookResponse0\x01\x32\xbb\x01\n\x05Maker\x12/\n\x08GetQuote\x12\x10.GetQuoteRequest\x1a\x11.GetQuoteResponse\x12\x35\n\nCheckQuote\x12\x12.CheckQuoteRequest\x1a\x13.CheckQuoteResponse\x12J\n\x11OrderStatusUpdate\x12\x19.OrderStatusUpdateRequest\x1a\x1a.OrderStatusUpdateResponse2E\n\tHotWallet\x12\x38\n\x0b\x43reateOrder\x12\x13.CreateOrderRequest\x1a\x14.CreateOrderResponse2R\n\x07Watcher\x12G\n\x10WatchTransaction\x12\x18.WatchTransactionRequest\x1a\x19.WatchTransactionResponseB\x06Z\x04grpcb\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ORDERBOOKMANAGER = _descriptor.ServiceDescriptor(
  name='OrderBookManager',
  full_name='OrderBookManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=32,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='OrderBook',
    full_name='OrderBookManager.OrderBook',
    index=0,
    containing_service=None,
    input_type=types__pb2._ORDERBOOKREQUEST,
    output_type=types__pb2._ORDERBOOKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Updates',
    full_name='OrderBookManager.Updates',
    index=1,
    containing_service=None,
    input_type=types__pb2._ORDERBOOKUPDATESREQUEST,
    output_type=types__pb2._ORDERBOOKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERBOOKMANAGER)

DESCRIPTOR.services_by_name['OrderBookManager'] = _ORDERBOOKMANAGER


_MAKER = _descriptor.ServiceDescriptor(
  name='Maker',
  full_name='Maker',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=164,
  serialized_end=351,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetQuote',
    full_name='Maker.GetQuote',
    index=0,
    containing_service=None,
    input_type=types__pb2._GETQUOTEREQUEST,
    output_type=types__pb2._GETQUOTERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckQuote',
    full_name='Maker.CheckQuote',
    index=1,
    containing_service=None,
    input_type=types__pb2._CHECKQUOTEREQUEST,
    output_type=types__pb2._CHECKQUOTERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OrderStatusUpdate',
    full_name='Maker.OrderStatusUpdate',
    index=2,
    containing_service=None,
    input_type=types__pb2._ORDERSTATUSUPDATEREQUEST,
    output_type=types__pb2._ORDERSTATUSUPDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAKER)

DESCRIPTOR.services_by_name['Maker'] = _MAKER


_HOTWALLET = _descriptor.ServiceDescriptor(
  name='HotWallet',
  full_name='HotWallet',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=353,
  serialized_end=422,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOrder',
    full_name='HotWallet.CreateOrder',
    index=0,
    containing_service=None,
    input_type=types__pb2._CREATEORDERREQUEST,
    output_type=types__pb2._CREATEORDERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOTWALLET)

DESCRIPTOR.services_by_name['HotWallet'] = _HOTWALLET


_WATCHER = _descriptor.ServiceDescriptor(
  name='Watcher',
  full_name='Watcher',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=424,
  serialized_end=506,
  methods=[
  _descriptor.MethodDescriptor(
    name='WatchTransaction',
    full_name='Watcher.WatchTransaction',
    index=0,
    containing_service=None,
    input_type=types__pb2._WATCHTRANSACTIONREQUEST,
    output_type=types__pb2._WATCHTRANSACTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WATCHER)

DESCRIPTOR.services_by_name['Watcher'] = _WATCHER

# @@protoc_insertion_point(module_scope)