version: '3.3'

services:
  dealer:
    depends_on:
      - db
      - maker
      - hwd
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - DEALER_DB=postgres
      - DEALER_DSN="host=db user=postgres password=postgres sslmode=disable"

  hwd:
    restart: always
    command: ["--eth", "ws://eth:8545", "--bind", "hwd:8000"]
    depends_on:
      - eth

  obm:
    command: ["--exchange", "coinbase:ETH/USD,DAI/USDC,ZRX/USD", "--exchange", "binance:ETH/USDT,ZRX/ETH,ZRX/USDT", "--bind", "0.0.0.0:8000"]

  watcher:
    restart: always
    command: ["--eth", "ws://eth:8545", "-m", "maker:8000", "-p", "8000"]
    depends_on: 
      - eth

  maker:
    restart: always
    environment: 
      - REDIS_HOST=redis
      - OBM_CHANNEL=obm:8000
      - BIND_ADDRESS=maker:8000
    depends_on:
      - obm
      - redis

  eth:
    image: gcr.io/zaidan-eth-net/0x-snapshot:v3
    ports:
      - 8545:8545
  
  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    ports:
      - 5432:5432
