version: '3.3'

services:
  dealer:
    image: gcr.io/zaidan-io/dealer

  obm:
    image: gcr.io/zaidan-io/obm

  hwd:
    image: gcr.io/zaidan-io/hwd
  
  maker:
    image: gcr.io/zaidan-io/maker

  maker:
    image: gcr.io/zaidan-io/maker

  watcher:
    image: gcr.io/zaidan-io/watcher
