version: '3.3'

services:
  dealer:
    depends_on:
      - db
      - maker
      - hwd
    environment:
      - DEALER_DSN="host=192.168.16.2 user=dealer password=password dbname=dealer sslmode=disable"
      - DEALER_DB=postgres
    ports:
      - 8000:8000

  hwd:
    restart: always
    command: ["--eth", "ws://eth:8545", "--bind", "hwd:8000"]
    depends_on:
      - eth

  obm:
    command: ["--exchange", "coinbase:ETH/USD,DAI/USDC", "--bind", "0.0.0.0:8000"]

  maker:
    restart: always
    environment: 
      - REDIS_HOST=redis
      - OBM_CHANNEL=obm:8000
      - BIND_ADDRESS=maker:8000
    depends_on:
      - obm
      - redis

  eth:
    image: gcr.io/zaidan-eth-net/0x-snapshot:v3
    ports:
      - 8545:8545
  
  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dealer
    ports:
      - 5432:5432
