version: '3.3'

services:
  dealer:
    command: ["--maker", "maker:8000", "--hw", "hwd:8000"]
    image: gcr.io/zaidan-io/dealer

  obm:
    image: gcr.io/zaidan-io/obm

  hwd:
    image: gcr.io/zaidan-io/hwd
  
  maker:
    image: gcr.io/zaidan-io/maker

  watcher:
    image: gcr.io/zaidan-io/watcher

  hedger:
    image: gcr.io/zaidan-io/hedger
