version: '3.3'

services:
  dealer:
    image: gcr.io/zaidan-io/dealer
    ports:
      - 8000

  obm:
    image: gcr.io/zaidan-io/obm
    command: ["--exchange", "coinbase:BTC/USD"]
    ports:
      - 8000

  hwd:
    image: gcr.io/zaidan-io/hwd

  watcher:
    image: gcr.io/zaidan-io/watcher
