# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import obm_pb2 as obm__pb2


class OrderBookManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OrderBook = channel.unary_unary(
        '/OrderBookManager/OrderBook',
        request_serializer=obm__pb2.OrderBookRequest.SerializeToString,
        response_deserializer=obm__pb2.OrderBookResponse.FromString,
        )


class OrderBookManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OrderBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderBookManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OrderBook': grpc.unary_unary_rpc_method_handler(
          servicer.OrderBook,
          request_deserializer=obm__pb2.OrderBookRequest.FromString,
          response_serializer=obm__pb2.OrderBookResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OrderBookManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
