# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: obm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='obm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tobm.proto\"4\n\x10OrderBookRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"1\n\x0eOrderBookEntry\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x01\"\x87\x01\n\x11OrderBookResponse\x12\x12\n\nlastUpdate\x18\x01 \x01(\x03\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x1d\n\x04\x61sks\x18\x04 \x03(\x0b\x32\x0f.OrderBookEntry\x12\x1d\n\x04\x62ids\x18\x05 \x03(\x0b\x32\x0f.OrderBookEntry2F\n\x10OrderBookManager\x12\x32\n\tOrderBook\x12\x11.OrderBookRequest\x1a\x12.OrderBookResponseb\x06proto3')
)




_ORDERBOOKREQUEST = _descriptor.Descriptor(
  name='OrderBookRequest',
  full_name='OrderBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='OrderBookRequest.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='OrderBookRequest.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=65,
)


_ORDERBOOKENTRY = _descriptor.Descriptor(
  name='OrderBookEntry',
  full_name='OrderBookEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='OrderBookEntry.price', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='OrderBookEntry.quantity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=116,
)


_ORDERBOOKRESPONSE = _descriptor.Descriptor(
  name='OrderBookResponse',
  full_name='OrderBookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lastUpdate', full_name='OrderBookResponse.lastUpdate', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='OrderBookResponse.exchange', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='OrderBookResponse.symbol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asks', full_name='OrderBookResponse.asks', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bids', full_name='OrderBookResponse.bids', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=254,
)

_ORDERBOOKRESPONSE.fields_by_name['asks'].message_type = _ORDERBOOKENTRY
_ORDERBOOKRESPONSE.fields_by_name['bids'].message_type = _ORDERBOOKENTRY
DESCRIPTOR.message_types_by_name['OrderBookRequest'] = _ORDERBOOKREQUEST
DESCRIPTOR.message_types_by_name['OrderBookEntry'] = _ORDERBOOKENTRY
DESCRIPTOR.message_types_by_name['OrderBookResponse'] = _ORDERBOOKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderBookRequest = _reflection.GeneratedProtocolMessageType('OrderBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERBOOKREQUEST,
  '__module__' : 'obm_pb2'
  # @@protoc_insertion_point(class_scope:OrderBookRequest)
  })
_sym_db.RegisterMessage(OrderBookRequest)

OrderBookEntry = _reflection.GeneratedProtocolMessageType('OrderBookEntry', (_message.Message,), {
  'DESCRIPTOR' : _ORDERBOOKENTRY,
  '__module__' : 'obm_pb2'
  # @@protoc_insertion_point(class_scope:OrderBookEntry)
  })
_sym_db.RegisterMessage(OrderBookEntry)

OrderBookResponse = _reflection.GeneratedProtocolMessageType('OrderBookResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERBOOKRESPONSE,
  '__module__' : 'obm_pb2'
  # @@protoc_insertion_point(class_scope:OrderBookResponse)
  })
_sym_db.RegisterMessage(OrderBookResponse)



_ORDERBOOKMANAGER = _descriptor.ServiceDescriptor(
  name='OrderBookManager',
  full_name='OrderBookManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=256,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='OrderBook',
    full_name='OrderBookManager.OrderBook',
    index=0,
    containing_service=None,
    input_type=_ORDERBOOKREQUEST,
    output_type=_ORDERBOOKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERBOOKMANAGER)

DESCRIPTOR.services_by_name['OrderBookManager'] = _ORDERBOOKMANAGER

# @@protoc_insertion_point(module_scope)
