// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Order book manager
type OrderBookEntry struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64  `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookEntry) Reset()         { *m = OrderBookEntry{} }
func (m *OrderBookEntry) String() string { return proto.CompactTextString(m) }
func (*OrderBookEntry) ProtoMessage()    {}
func (*OrderBookEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *OrderBookEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookEntry.Unmarshal(m, b)
}
func (m *OrderBookEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookEntry.Marshal(b, m, deterministic)
}
func (m *OrderBookEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookEntry.Merge(m, src)
}
func (m *OrderBookEntry) XXX_Size() int {
	return xxx_messageInfo_OrderBookEntry.Size(m)
}
func (m *OrderBookEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookEntry proto.InternalMessageInfo

func (m *OrderBookEntry) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderBookEntry) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderBookRequest struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookRequest) Reset()         { *m = OrderBookRequest{} }
func (m *OrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*OrderBookRequest) ProtoMessage()    {}
func (*OrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *OrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookRequest.Unmarshal(m, b)
}
func (m *OrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookRequest.Marshal(b, m, deterministic)
}
func (m *OrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookRequest.Merge(m, src)
}
func (m *OrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_OrderBookRequest.Size(m)
}
func (m *OrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookRequest proto.InternalMessageInfo

func (m *OrderBookRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderBookRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type OrderBookUpdatesRequest struct {
	Request              *OrderBookRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit                uint32            `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrderBookUpdatesRequest) Reset()         { *m = OrderBookUpdatesRequest{} }
func (m *OrderBookUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*OrderBookUpdatesRequest) ProtoMessage()    {}
func (*OrderBookUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *OrderBookUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookUpdatesRequest.Unmarshal(m, b)
}
func (m *OrderBookUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookUpdatesRequest.Marshal(b, m, deterministic)
}
func (m *OrderBookUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookUpdatesRequest.Merge(m, src)
}
func (m *OrderBookUpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_OrderBookUpdatesRequest.Size(m)
}
func (m *OrderBookUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookUpdatesRequest proto.InternalMessageInfo

func (m *OrderBookUpdatesRequest) GetRequest() *OrderBookRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *OrderBookUpdatesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type OrderBookResponse struct {
	LastUpdate           int64             `protobuf:"varint,1,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Exchange             string            `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string            `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Asks                 []*OrderBookEntry `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*OrderBookEntry `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrderBookResponse) Reset()         { *m = OrderBookResponse{} }
func (m *OrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*OrderBookResponse) ProtoMessage()    {}
func (*OrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *OrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookResponse.Unmarshal(m, b)
}
func (m *OrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookResponse.Marshal(b, m, deterministic)
}
func (m *OrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookResponse.Merge(m, src)
}
func (m *OrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_OrderBookResponse.Size(m)
}
func (m *OrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookResponse proto.InternalMessageInfo

func (m *OrderBookResponse) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *OrderBookResponse) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderBookResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderBookResponse) GetAsks() []*OrderBookEntry {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBookResponse) GetBids() []*OrderBookEntry {
	if m != nil {
		return m.Bids
	}
	return nil
}

// Maker
type GetQuoteRequest struct {
	QuoteId              string   `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	TakerAsset           string   `protobuf:"bytes,2,opt,name=taker_asset,json=takerAsset,proto3" json:"taker_asset,omitempty"`
	MakerAsset           string   `protobuf:"bytes,3,opt,name=maker_asset,json=makerAsset,proto3" json:"maker_asset,omitempty"`
	TakerSize            string   `protobuf:"bytes,4,opt,name=taker_size,json=takerSize,proto3" json:"taker_size,omitempty"`
	MakerSize            string   `protobuf:"bytes,5,opt,name=maker_size,json=makerSize,proto3" json:"maker_size,omitempty"`
	TakerAddress         string   `protobuf:"bytes,6,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuoteRequest) Reset()         { *m = GetQuoteRequest{} }
func (m *GetQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuoteRequest) ProtoMessage()    {}
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *GetQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteRequest.Unmarshal(m, b)
}
func (m *GetQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteRequest.Marshal(b, m, deterministic)
}
func (m *GetQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteRequest.Merge(m, src)
}
func (m *GetQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuoteRequest.Size(m)
}
func (m *GetQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteRequest proto.InternalMessageInfo

func (m *GetQuoteRequest) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *GetQuoteRequest) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *GetQuoteRequest) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *GetQuoteRequest) GetTakerSize() string {
	if m != nil {
		return m.TakerSize
	}
	return ""
}

func (m *GetQuoteRequest) GetMakerSize() string {
	if m != nil {
		return m.MakerSize
	}
	return ""
}

func (m *GetQuoteRequest) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

type GetQuoteResponse struct {
	QuoteId              string   `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	Expiration           string   `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	TakerAsset           string   `protobuf:"bytes,3,opt,name=taker_asset,json=takerAsset,proto3" json:"taker_asset,omitempty"`
	MakerAsset           string   `protobuf:"bytes,4,opt,name=maker_asset,json=makerAsset,proto3" json:"maker_asset,omitempty"`
	TakerSize            string   `protobuf:"bytes,5,opt,name=taker_size,json=takerSize,proto3" json:"taker_size,omitempty"`
	MakerSize            string   `protobuf:"bytes,6,opt,name=maker_size,json=makerSize,proto3" json:"maker_size,omitempty"`
	Fee                  string   `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuoteResponse) Reset()         { *m = GetQuoteResponse{} }
func (m *GetQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuoteResponse) ProtoMessage()    {}
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *GetQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteResponse.Unmarshal(m, b)
}
func (m *GetQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteResponse.Marshal(b, m, deterministic)
}
func (m *GetQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteResponse.Merge(m, src)
}
func (m *GetQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuoteResponse.Size(m)
}
func (m *GetQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteResponse proto.InternalMessageInfo

func (m *GetQuoteResponse) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *GetQuoteResponse) GetExpiration() string {
	if m != nil {
		return m.Expiration
	}
	return ""
}

func (m *GetQuoteResponse) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *GetQuoteResponse) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *GetQuoteResponse) GetTakerSize() string {
	if m != nil {
		return m.TakerSize
	}
	return ""
}

func (m *GetQuoteResponse) GetMakerSize() string {
	if m != nil {
		return m.MakerSize
	}
	return ""
}

func (m *GetQuoteResponse) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

type CheckQuoteRequest struct {
	QuoteId              string   `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckQuoteRequest) Reset()         { *m = CheckQuoteRequest{} }
func (m *CheckQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*CheckQuoteRequest) ProtoMessage()    {}
func (*CheckQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *CheckQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckQuoteRequest.Unmarshal(m, b)
}
func (m *CheckQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckQuoteRequest.Marshal(b, m, deterministic)
}
func (m *CheckQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckQuoteRequest.Merge(m, src)
}
func (m *CheckQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_CheckQuoteRequest.Size(m)
}
func (m *CheckQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckQuoteRequest proto.InternalMessageInfo

func (m *CheckQuoteRequest) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

type CheckQuoteResponse struct {
	QuoteId              string   `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	IsValid              bool     `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Status               uint32   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckQuoteResponse) Reset()         { *m = CheckQuoteResponse{} }
func (m *CheckQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*CheckQuoteResponse) ProtoMessage()    {}
func (*CheckQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *CheckQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckQuoteResponse.Unmarshal(m, b)
}
func (m *CheckQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckQuoteResponse.Marshal(b, m, deterministic)
}
func (m *CheckQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckQuoteResponse.Merge(m, src)
}
func (m *CheckQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_CheckQuoteResponse.Size(m)
}
func (m *CheckQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckQuoteResponse proto.InternalMessageInfo

func (m *CheckQuoteResponse) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *CheckQuoteResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *CheckQuoteResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type OrderStatusUpdateRequest struct {
	QuoteId              string   `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatusUpdateRequest) Reset()         { *m = OrderStatusUpdateRequest{} }
func (m *OrderStatusUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*OrderStatusUpdateRequest) ProtoMessage()    {}
func (*OrderStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *OrderStatusUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusUpdateRequest.Unmarshal(m, b)
}
func (m *OrderStatusUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusUpdateRequest.Marshal(b, m, deterministic)
}
func (m *OrderStatusUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusUpdateRequest.Merge(m, src)
}
func (m *OrderStatusUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_OrderStatusUpdateRequest.Size(m)
}
func (m *OrderStatusUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusUpdateRequest proto.InternalMessageInfo

func (m *OrderStatusUpdateRequest) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *OrderStatusUpdateRequest) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type OrderStatusUpdateResponse struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatusUpdateResponse) Reset()         { *m = OrderStatusUpdateResponse{} }
func (m *OrderStatusUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*OrderStatusUpdateResponse) ProtoMessage()    {}
func (*OrderStatusUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *OrderStatusUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusUpdateResponse.Unmarshal(m, b)
}
func (m *OrderStatusUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusUpdateResponse.Marshal(b, m, deterministic)
}
func (m *OrderStatusUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusUpdateResponse.Merge(m, src)
}
func (m *OrderStatusUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_OrderStatusUpdateResponse.Size(m)
}
func (m *OrderStatusUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusUpdateResponse proto.InternalMessageInfo

func (m *OrderStatusUpdateResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Hot wallet
type Order struct {
	ChainId               uint64   `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ExchangeAddress       string   `protobuf:"bytes,2,opt,name=exchange_address,json=exchangeAddress,proto3" json:"exchange_address,omitempty"`
	MakerAddress          string   `protobuf:"bytes,3,opt,name=maker_address,json=makerAddress,proto3" json:"maker_address,omitempty"`
	MakerAssetData        string   `protobuf:"bytes,4,opt,name=maker_asset_data,json=makerAssetData,proto3" json:"maker_asset_data,omitempty"`
	MakerFeeAssetData     string   `protobuf:"bytes,5,opt,name=maker_fee_asset_data,json=makerFeeAssetData,proto3" json:"maker_fee_asset_data,omitempty"`
	MakerAssetAmount      string   `protobuf:"bytes,6,opt,name=maker_asset_amount,json=makerAssetAmount,proto3" json:"maker_asset_amount,omitempty"`
	MakerFee              string   `protobuf:"bytes,7,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerAddress          string   `protobuf:"bytes,8,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	TakerAssetData        string   `protobuf:"bytes,9,opt,name=taker_asset_data,json=takerAssetData,proto3" json:"taker_asset_data,omitempty"`
	TakerFeeAssetData     string   `protobuf:"bytes,10,opt,name=taker_fee_asset_data,json=takerFeeAssetData,proto3" json:"taker_fee_asset_data,omitempty"`
	TakerAssetAmount      string   `protobuf:"bytes,11,opt,name=taker_asset_amount,json=takerAssetAmount,proto3" json:"taker_asset_amount,omitempty"`
	TakerFee              string   `protobuf:"bytes,12,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	SenderAddress         string   `protobuf:"bytes,13,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	FeeRecipientAddress   string   `protobuf:"bytes,14,opt,name=fee_recipient_address,json=feeRecipientAddress,proto3" json:"fee_recipient_address,omitempty"`
	ExpirationTimeSeconds string   `protobuf:"bytes,15,opt,name=expiration_time_seconds,json=expirationTimeSeconds,proto3" json:"expiration_time_seconds,omitempty"`
	Salt                  string   `protobuf:"bytes,16,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Order) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *Order) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *Order) GetMakerAssetData() string {
	if m != nil {
		return m.MakerAssetData
	}
	return ""
}

func (m *Order) GetMakerFeeAssetData() string {
	if m != nil {
		return m.MakerFeeAssetData
	}
	return ""
}

func (m *Order) GetMakerAssetAmount() string {
	if m != nil {
		return m.MakerAssetAmount
	}
	return ""
}

func (m *Order) GetMakerFee() string {
	if m != nil {
		return m.MakerFee
	}
	return ""
}

func (m *Order) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *Order) GetTakerAssetData() string {
	if m != nil {
		return m.TakerAssetData
	}
	return ""
}

func (m *Order) GetTakerFeeAssetData() string {
	if m != nil {
		return m.TakerFeeAssetData
	}
	return ""
}

func (m *Order) GetTakerAssetAmount() string {
	if m != nil {
		return m.TakerAssetAmount
	}
	return ""
}

func (m *Order) GetTakerFee() string {
	if m != nil {
		return m.TakerFee
	}
	return ""
}

func (m *Order) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *Order) GetFeeRecipientAddress() string {
	if m != nil {
		return m.FeeRecipientAddress
	}
	return ""
}

func (m *Order) GetExpirationTimeSeconds() string {
	if m != nil {
		return m.ExpirationTimeSeconds
	}
	return ""
}

func (m *Order) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

type SignedOrder struct {
	ChainId               uint64   `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ExchangeAddress       string   `protobuf:"bytes,2,opt,name=exchange_address,json=exchangeAddress,proto3" json:"exchange_address,omitempty"`
	MakerAddress          string   `protobuf:"bytes,3,opt,name=maker_address,json=makerAddress,proto3" json:"maker_address,omitempty"`
	MakerAssetData        string   `protobuf:"bytes,4,opt,name=maker_asset_data,json=makerAssetData,proto3" json:"maker_asset_data,omitempty"`
	MakerFeeAssetData     string   `protobuf:"bytes,5,opt,name=maker_fee_asset_data,json=makerFeeAssetData,proto3" json:"maker_fee_asset_data,omitempty"`
	MakerAssetAmount      string   `protobuf:"bytes,6,opt,name=maker_asset_amount,json=makerAssetAmount,proto3" json:"maker_asset_amount,omitempty"`
	MakerFee              string   `protobuf:"bytes,7,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerAddress          string   `protobuf:"bytes,8,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	TakerAssetData        string   `protobuf:"bytes,9,opt,name=taker_asset_data,json=takerAssetData,proto3" json:"taker_asset_data,omitempty"`
	TakerFeeAssetData     string   `protobuf:"bytes,10,opt,name=taker_fee_asset_data,json=takerFeeAssetData,proto3" json:"taker_fee_asset_data,omitempty"`
	TakerAssetAmount      string   `protobuf:"bytes,11,opt,name=taker_asset_amount,json=takerAssetAmount,proto3" json:"taker_asset_amount,omitempty"`
	TakerFee              string   `protobuf:"bytes,12,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	SenderAddress         string   `protobuf:"bytes,13,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	FeeRecipientAddress   string   `protobuf:"bytes,14,opt,name=fee_recipient_address,json=feeRecipientAddress,proto3" json:"fee_recipient_address,omitempty"`
	ExpirationTimeSeconds string   `protobuf:"bytes,15,opt,name=expiration_time_seconds,json=expirationTimeSeconds,proto3" json:"expiration_time_seconds,omitempty"`
	Salt                  string   `protobuf:"bytes,16,opt,name=salt,proto3" json:"salt,omitempty"`
	Signature             string   `protobuf:"bytes,17,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SignedOrder) Reset()         { *m = SignedOrder{} }
func (m *SignedOrder) String() string { return proto.CompactTextString(m) }
func (*SignedOrder) ProtoMessage()    {}
func (*SignedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *SignedOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedOrder.Unmarshal(m, b)
}
func (m *SignedOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedOrder.Marshal(b, m, deterministic)
}
func (m *SignedOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedOrder.Merge(m, src)
}
func (m *SignedOrder) XXX_Size() int {
	return xxx_messageInfo_SignedOrder.Size(m)
}
func (m *SignedOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SignedOrder proto.InternalMessageInfo

func (m *SignedOrder) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *SignedOrder) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *SignedOrder) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *SignedOrder) GetMakerAssetData() string {
	if m != nil {
		return m.MakerAssetData
	}
	return ""
}

func (m *SignedOrder) GetMakerFeeAssetData() string {
	if m != nil {
		return m.MakerFeeAssetData
	}
	return ""
}

func (m *SignedOrder) GetMakerAssetAmount() string {
	if m != nil {
		return m.MakerAssetAmount
	}
	return ""
}

func (m *SignedOrder) GetMakerFee() string {
	if m != nil {
		return m.MakerFee
	}
	return ""
}

func (m *SignedOrder) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *SignedOrder) GetTakerAssetData() string {
	if m != nil {
		return m.TakerAssetData
	}
	return ""
}

func (m *SignedOrder) GetTakerFeeAssetData() string {
	if m != nil {
		return m.TakerFeeAssetData
	}
	return ""
}

func (m *SignedOrder) GetTakerAssetAmount() string {
	if m != nil {
		return m.TakerAssetAmount
	}
	return ""
}

func (m *SignedOrder) GetTakerFee() string {
	if m != nil {
		return m.TakerFee
	}
	return ""
}

func (m *SignedOrder) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *SignedOrder) GetFeeRecipientAddress() string {
	if m != nil {
		return m.FeeRecipientAddress
	}
	return ""
}

func (m *SignedOrder) GetExpirationTimeSeconds() string {
	if m != nil {
		return m.ExpirationTimeSeconds
	}
	return ""
}

func (m *SignedOrder) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *SignedOrder) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type SignOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOrderRequest) Reset()         { *m = SignOrderRequest{} }
func (m *SignOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SignOrderRequest) ProtoMessage()    {}
func (*SignOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *SignOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOrderRequest.Unmarshal(m, b)
}
func (m *SignOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOrderRequest.Marshal(b, m, deterministic)
}
func (m *SignOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOrderRequest.Merge(m, src)
}
func (m *SignOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SignOrderRequest.Size(m)
}
func (m *SignOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOrderRequest proto.InternalMessageInfo

func (m *SignOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type SignOrderResponse struct {
	SignedOrder          *SignedOrder `protobuf:"bytes,1,opt,name=signedOrder,proto3" json:"signedOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignOrderResponse) Reset()         { *m = SignOrderResponse{} }
func (m *SignOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SignOrderResponse) ProtoMessage()    {}
func (*SignOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *SignOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOrderResponse.Unmarshal(m, b)
}
func (m *SignOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOrderResponse.Marshal(b, m, deterministic)
}
func (m *SignOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOrderResponse.Merge(m, src)
}
func (m *SignOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SignOrderResponse.Size(m)
}
func (m *SignOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOrderResponse proto.InternalMessageInfo

func (m *SignOrderResponse) GetSignedOrder() *SignedOrder {
	if m != nil {
		return m.SignedOrder
	}
	return nil
}

type HashOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashOrderRequest) Reset()         { *m = HashOrderRequest{} }
func (m *HashOrderRequest) String() string { return proto.CompactTextString(m) }
func (*HashOrderRequest) ProtoMessage()    {}
func (*HashOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *HashOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashOrderRequest.Unmarshal(m, b)
}
func (m *HashOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashOrderRequest.Marshal(b, m, deterministic)
}
func (m *HashOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashOrderRequest.Merge(m, src)
}
func (m *HashOrderRequest) XXX_Size() int {
	return xxx_messageInfo_HashOrderRequest.Size(m)
}
func (m *HashOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashOrderRequest proto.InternalMessageInfo

func (m *HashOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type HashOrderResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashOrderResponse) Reset()         { *m = HashOrderResponse{} }
func (m *HashOrderResponse) String() string { return proto.CompactTextString(m) }
func (*HashOrderResponse) ProtoMessage()    {}
func (*HashOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{15}
}

func (m *HashOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashOrderResponse.Unmarshal(m, b)
}
func (m *HashOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashOrderResponse.Marshal(b, m, deterministic)
}
func (m *HashOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashOrderResponse.Merge(m, src)
}
func (m *HashOrderResponse) XXX_Size() int {
	return xxx_messageInfo_HashOrderResponse.Size(m)
}
func (m *HashOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashOrderResponse proto.InternalMessageInfo

func (m *HashOrderResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type CreateOrderRequest struct {
	TakerAddress          string   `protobuf:"bytes,1,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	MakerAssetAddress     string   `protobuf:"bytes,2,opt,name=maker_asset_address,json=makerAssetAddress,proto3" json:"maker_asset_address,omitempty"`
	TakerAssetAddress     string   `protobuf:"bytes,3,opt,name=taker_asset_address,json=takerAssetAddress,proto3" json:"taker_asset_address,omitempty"`
	MakerAssetAmount      string   `protobuf:"bytes,4,opt,name=maker_asset_amount,json=makerAssetAmount,proto3" json:"maker_asset_amount,omitempty"`
	TakerAssetAmount      string   `protobuf:"bytes,5,opt,name=taker_asset_amount,json=takerAssetAmount,proto3" json:"taker_asset_amount,omitempty"`
	ExpirationTimeSeconds string   `protobuf:"bytes,6,opt,name=expiration_time_seconds,json=expirationTimeSeconds,proto3" json:"expiration_time_seconds,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{16}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *CreateOrderRequest) GetMakerAssetAddress() string {
	if m != nil {
		return m.MakerAssetAddress
	}
	return ""
}

func (m *CreateOrderRequest) GetTakerAssetAddress() string {
	if m != nil {
		return m.TakerAssetAddress
	}
	return ""
}

func (m *CreateOrderRequest) GetMakerAssetAmount() string {
	if m != nil {
		return m.MakerAssetAmount
	}
	return ""
}

func (m *CreateOrderRequest) GetTakerAssetAmount() string {
	if m != nil {
		return m.TakerAssetAmount
	}
	return ""
}

func (m *CreateOrderRequest) GetExpirationTimeSeconds() string {
	if m != nil {
		return m.ExpirationTimeSeconds
	}
	return ""
}

type CreateOrderResponse struct {
	Order                *SignedOrder `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Hash                 []byte       `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{17}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrder() *SignedOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *CreateOrderResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type WatchTransactionRequest struct {
	QuoteId              string   `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	TxHash               string   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchTransactionRequest) Reset()         { *m = WatchTransactionRequest{} }
func (m *WatchTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*WatchTransactionRequest) ProtoMessage()    {}
func (*WatchTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{18}
}

func (m *WatchTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchTransactionRequest.Unmarshal(m, b)
}
func (m *WatchTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchTransactionRequest.Marshal(b, m, deterministic)
}
func (m *WatchTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchTransactionRequest.Merge(m, src)
}
func (m *WatchTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_WatchTransactionRequest.Size(m)
}
func (m *WatchTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchTransactionRequest proto.InternalMessageInfo

func (m *WatchTransactionRequest) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *WatchTransactionRequest) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type WatchTransactionResponse struct {
	QuoteId              string   `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	TxHash               string   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	IsPending            bool     `protobuf:"varint,3,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	IsWatched            bool     `protobuf:"varint,4,opt,name=is_watched,json=isWatched,proto3" json:"is_watched,omitempty"`
	TxStatus             uint32   `protobuf:"varint,5,opt,name=tx_status,json=txStatus,proto3" json:"tx_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchTransactionResponse) Reset()         { *m = WatchTransactionResponse{} }
func (m *WatchTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*WatchTransactionResponse) ProtoMessage()    {}
func (*WatchTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{19}
}

func (m *WatchTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchTransactionResponse.Unmarshal(m, b)
}
func (m *WatchTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchTransactionResponse.Marshal(b, m, deterministic)
}
func (m *WatchTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchTransactionResponse.Merge(m, src)
}
func (m *WatchTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_WatchTransactionResponse.Size(m)
}
func (m *WatchTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchTransactionResponse proto.InternalMessageInfo

func (m *WatchTransactionResponse) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *WatchTransactionResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *WatchTransactionResponse) GetIsPending() bool {
	if m != nil {
		return m.IsPending
	}
	return false
}

func (m *WatchTransactionResponse) GetIsWatched() bool {
	if m != nil {
		return m.IsWatched
	}
	return false
}

func (m *WatchTransactionResponse) GetTxStatus() uint32 {
	if m != nil {
		return m.TxStatus
	}
	return 0
}

// Dealer
type Quote struct {
	QuoteId              string       `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	MakerAssetTicker     string       `protobuf:"bytes,2,opt,name=maker_asset_ticker,json=makerAssetTicker,proto3" json:"maker_asset_ticker,omitempty"`
	TakerAssetTicker     string       `protobuf:"bytes,3,opt,name=taker_asset_ticker,json=takerAssetTicker,proto3" json:"taker_asset_ticker,omitempty"`
	MakerAssetSize       string       `protobuf:"bytes,4,opt,name=maker_asset_size,json=makerAssetSize,proto3" json:"maker_asset_size,omitempty"`
	QuoteAssetSize       string       `protobuf:"bytes,5,opt,name=quote_asset_size,json=quoteAssetSize,proto3" json:"quote_asset_size,omitempty"`
	Expiration           int64        `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	ServerTime           int64        `protobuf:"varint,7,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	OrderHash            string       `protobuf:"bytes,8,opt,name=order_hash,json=orderHash,proto3" json:"order_hash,omitempty"`
	Order                *SignedOrder `protobuf:"bytes,9,opt,name=order,proto3" json:"order,omitempty"`
	FillTx               string       `protobuf:"bytes,10,opt,name=fill_tx,json=fillTx,proto3" json:"fill_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{20}
}

func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (m *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(m, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *Quote) GetMakerAssetTicker() string {
	if m != nil {
		return m.MakerAssetTicker
	}
	return ""
}

func (m *Quote) GetTakerAssetTicker() string {
	if m != nil {
		return m.TakerAssetTicker
	}
	return ""
}

func (m *Quote) GetMakerAssetSize() string {
	if m != nil {
		return m.MakerAssetSize
	}
	return ""
}

func (m *Quote) GetQuoteAssetSize() string {
	if m != nil {
		return m.QuoteAssetSize
	}
	return ""
}

func (m *Quote) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *Quote) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *Quote) GetOrderHash() string {
	if m != nil {
		return m.OrderHash
	}
	return ""
}

func (m *Quote) GetOrder() *SignedOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Quote) GetFillTx() string {
	if m != nil {
		return m.FillTx
	}
	return ""
}

type Trade struct {
	QuoteId              string       `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	MarketId             string       `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OrderHash            string       `protobuf:"bytes,3,opt,name=order_hash,json=orderHash,proto3" json:"order_hash,omitempty"`
	TransactionHash      string       `protobuf:"bytes,4,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	TakerAddress         string       `protobuf:"bytes,5,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	Timestamp            int64        `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MakerAssetTicker     string       `protobuf:"bytes,7,opt,name=maker_asset_ticker,json=makerAssetTicker,proto3" json:"maker_asset_ticker,omitempty"`
	TakerAssetTicker     string       `protobuf:"bytes,8,opt,name=taker_asset_ticker,json=takerAssetTicker,proto3" json:"taker_asset_ticker,omitempty"`
	MakerAssetAmount     string       `protobuf:"bytes,9,opt,name=maker_asset_amount,json=makerAssetAmount,proto3" json:"maker_asset_amount,omitempty"`
	TakerAssetAmount     string       `protobuf:"bytes,10,opt,name=taker_asset_amount,json=takerAssetAmount,proto3" json:"taker_asset_amount,omitempty"`
	Order                *SignedOrder `protobuf:"bytes,11,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{21}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetQuoteId() string {
	if m != nil {
		return m.QuoteId
	}
	return ""
}

func (m *Trade) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *Trade) GetOrderHash() string {
	if m != nil {
		return m.OrderHash
	}
	return ""
}

func (m *Trade) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Trade) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *Trade) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Trade) GetMakerAssetTicker() string {
	if m != nil {
		return m.MakerAssetTicker
	}
	return ""
}

func (m *Trade) GetTakerAssetTicker() string {
	if m != nil {
		return m.TakerAssetTicker
	}
	return ""
}

func (m *Trade) GetMakerAssetAmount() string {
	if m != nil {
		return m.MakerAssetAmount
	}
	return ""
}

func (m *Trade) GetTakerAssetAmount() string {
	if m != nil {
		return m.TakerAssetAmount
	}
	return ""
}

func (m *Trade) GetOrder() *SignedOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

type Asset struct {
	Ticker               string   `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Decimals             uint32   `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	NetworkId            uint32   `protobuf:"varint,4,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{22}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Asset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Asset) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *Asset) GetNetworkId() uint32 {
	if m != nil {
		return m.NetworkId
	}
	return 0
}

func (m *Asset) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderBookEntry)(nil), "OrderBookEntry")
	proto.RegisterType((*OrderBookRequest)(nil), "OrderBookRequest")
	proto.RegisterType((*OrderBookUpdatesRequest)(nil), "OrderBookUpdatesRequest")
	proto.RegisterType((*OrderBookResponse)(nil), "OrderBookResponse")
	proto.RegisterType((*GetQuoteRequest)(nil), "GetQuoteRequest")
	proto.RegisterType((*GetQuoteResponse)(nil), "GetQuoteResponse")
	proto.RegisterType((*CheckQuoteRequest)(nil), "CheckQuoteRequest")
	proto.RegisterType((*CheckQuoteResponse)(nil), "CheckQuoteResponse")
	proto.RegisterType((*OrderStatusUpdateRequest)(nil), "OrderStatusUpdateRequest")
	proto.RegisterType((*OrderStatusUpdateResponse)(nil), "OrderStatusUpdateResponse")
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*SignedOrder)(nil), "SignedOrder")
	proto.RegisterType((*SignOrderRequest)(nil), "SignOrderRequest")
	proto.RegisterType((*SignOrderResponse)(nil), "SignOrderResponse")
	proto.RegisterType((*HashOrderRequest)(nil), "HashOrderRequest")
	proto.RegisterType((*HashOrderResponse)(nil), "HashOrderResponse")
	proto.RegisterType((*CreateOrderRequest)(nil), "CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "CreateOrderResponse")
	proto.RegisterType((*WatchTransactionRequest)(nil), "WatchTransactionRequest")
	proto.RegisterType((*WatchTransactionResponse)(nil), "WatchTransactionResponse")
	proto.RegisterType((*Quote)(nil), "Quote")
	proto.RegisterType((*Trade)(nil), "Trade")
	proto.RegisterType((*Asset)(nil), "Asset")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 1246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdb, 0x6e, 0xe4, 0x44,
	0x13, 0xd6, 0x1c, 0x3c, 0x33, 0xae, 0xc9, 0x61, 0xc6, 0x7b, 0x88, 0xf7, 0xff, 0x03, 0xac, 0xbc,
	0x42, 0x64, 0x05, 0x1a, 0x50, 0x56, 0xe2, 0x7e, 0x13, 0x58, 0xc8, 0x45, 0x04, 0x38, 0x81, 0x95,
	0x10, 0x92, 0xd5, 0x19, 0x57, 0x32, 0xad, 0x19, 0xdb, 0xb3, 0xee, 0x9e, 0xdd, 0xc9, 0x3e, 0x01,
	0xe2, 0x49, 0xe0, 0x02, 0x2e, 0x78, 0x13, 0x9e, 0x80, 0x47, 0xe0, 0x15, 0x50, 0x57, 0xb7, 0x4f,
	0x73, 0x4a, 0x72, 0xc7, 0xc5, 0xde, 0xb9, 0x0e, 0x5d, 0x5d, 0x5f, 0xd5, 0xd7, 0xed, 0xb2, 0xa1,
	0x2b, 0xaf, 0xa7, 0x28, 0x06, 0xd3, 0x34, 0x91, 0x89, 0x77, 0x04, 0x3b, 0xdf, 0xa4, 0x21, 0xa6,
	0x47, 0x49, 0x32, 0xfe, 0x32, 0x96, 0xe9, 0xb5, 0x73, 0x1f, 0xac, 0x69, 0xca, 0x87, 0xe8, 0xd6,
	0x1e, 0xd7, 0x0e, 0x6a, 0xbe, 0x16, 0x9c, 0xff, 0x41, 0xe7, 0xd5, 0x8c, 0xc5, 0x92, 0xcb, 0x6b,
	0xb7, 0x4e, 0x86, 0x5c, 0xf6, 0x5e, 0x40, 0x2f, 0x8f, 0xe1, 0xe3, 0xab, 0x19, 0x0a, 0xa9, 0xfc,
	0x71, 0x3e, 0x1c, 0xb1, 0xf8, 0x4a, 0x07, 0xb2, 0xfd, 0x5c, 0x76, 0x1e, 0x42, 0x4b, 0x5c, 0x47,
	0x17, 0xc9, 0x84, 0x22, 0xd9, 0xbe, 0x91, 0xbc, 0x9f, 0x60, 0x2f, 0x8f, 0xf3, 0xfd, 0x34, 0x64,
	0x12, 0x45, 0x16, 0xee, 0x63, 0x68, 0xa7, 0xfa, 0x91, 0xa2, 0x75, 0x0f, 0xfb, 0x83, 0xc5, 0x2d,
	0xfd, 0xcc, 0x43, 0x21, 0x98, 0xf0, 0x88, 0x4b, 0x0a, 0xbf, 0xed, 0x6b, 0xc1, 0xfb, 0xb3, 0x06,
	0xfd, 0xd2, 0x1a, 0x31, 0x4d, 0x62, 0x81, 0xce, 0x07, 0xd0, 0x9d, 0x30, 0x21, 0x83, 0x19, 0xed,
	0x47, 0xc1, 0x1b, 0x3e, 0x28, 0x95, 0xce, 0xa0, 0x02, 0xa4, 0xbe, 0x16, 0x48, 0xa3, 0x0c, 0xc4,
	0x79, 0x02, 0x4d, 0x26, 0xc6, 0xc2, 0x6d, 0x3e, 0x6e, 0x1c, 0x74, 0x0f, 0x77, 0x07, 0xd5, 0x0a,
	0xfb, 0x64, 0x54, 0x4e, 0x17, 0x3c, 0x14, 0xae, 0xb5, 0xc6, 0x49, 0x19, 0xbd, 0xbf, 0x6a, 0xb0,
	0xfb, 0x15, 0xca, 0xef, 0x66, 0x89, 0xc4, 0xac, 0x16, 0x8f, 0x54, 0x2b, 0x12, 0x89, 0x01, 0x0f,
	0x4d, 0x69, 0xdb, 0x24, 0x9f, 0x84, 0x0a, 0x8d, 0x64, 0x63, 0x4c, 0x03, 0x26, 0x04, 0x4a, 0x93,
	0x2f, 0x90, 0xea, 0xb9, 0xd2, 0x28, 0x87, 0xa8, 0xe4, 0xa0, 0xd3, 0x86, 0xa8, 0x70, 0x78, 0x0f,
	0xb4, 0x7b, 0x20, 0xf8, 0x5b, 0x74, 0x9b, 0x64, 0xb7, 0x49, 0x73, 0xc6, 0xdf, 0xa2, 0x32, 0x47,
	0x85, 0xd9, 0xd2, 0xe6, 0x28, 0x37, 0x3f, 0x81, 0x6d, 0xb3, 0x7f, 0x18, 0xa6, 0x28, 0x84, 0xdb,
	0x22, 0x8f, 0x2d, 0x9d, 0x81, 0xd6, 0x79, 0x7f, 0xd7, 0xa0, 0x57, 0x60, 0x32, 0x7d, 0xd8, 0x00,
	0xea, 0x7d, 0x00, 0x9c, 0x4f, 0x79, 0xca, 0x24, 0x4f, 0xe2, 0x0c, 0x53, 0xa1, 0x59, 0x04, 0xdd,
	0xb8, 0x09, 0x74, 0xf3, 0x06, 0xd0, 0xd6, 0x66, 0xd0, 0xad, 0x45, 0xd0, 0x3d, 0x68, 0x5c, 0x22,
	0xba, 0x6d, 0xd2, 0xab, 0x47, 0x6f, 0x00, 0xfd, 0xe3, 0x11, 0x0e, 0xc7, 0xb7, 0x6c, 0x9b, 0x77,
	0x01, 0x4e, 0xd9, 0xff, 0xe6, 0x92, 0x3c, 0x82, 0x0e, 0x17, 0xc1, 0x6b, 0x36, 0xe1, 0x21, 0x15,
	0xa4, 0xe3, 0xb7, 0xb9, 0xf8, 0x41, 0x89, 0xc4, 0x49, 0xc9, 0xe4, 0x4c, 0x50, 0x21, 0xb6, 0x7d,
	0x23, 0x79, 0xa7, 0xe0, 0x12, 0xc3, 0xce, 0x48, 0xd4, 0xe4, 0xbe, 0x05, 0xa3, 0x8a, 0x70, 0xf5,
	0x4a, 0xb8, 0x67, 0xf0, 0x68, 0x45, 0x38, 0x93, 0x79, 0xb1, 0xa8, 0x56, 0x59, 0xf4, 0x8b, 0x05,
	0x16, 0xad, 0x52, 0x3b, 0x0e, 0x47, 0x8c, 0xc7, 0xd9, 0x8e, 0x4d, 0xbf, 0x4d, 0xf2, 0x49, 0xe8,
	0x3c, 0x85, 0x5e, 0x76, 0xc0, 0x72, 0x1a, 0xe9, 0xa6, 0xef, 0x66, 0x7a, 0xc3, 0x24, 0x45, 0xb7,
	0xa8, 0x42, 0x37, 0xdd, 0xfb, 0xad, 0xa8, 0x44, 0x37, 0xe7, 0x00, 0x7a, 0xa5, 0xee, 0x07, 0x21,
	0x93, 0xcc, 0x50, 0x60, 0xa7, 0xa0, 0xc0, 0x17, 0x4c, 0x32, 0xe7, 0x53, 0xb8, 0xaf, 0x3d, 0x2f,
	0x11, 0xcb, 0xde, 0x9a, 0x10, 0x7d, 0xb2, 0xbd, 0x40, 0x2c, 0x16, 0x7c, 0x02, 0x4e, 0x39, 0x34,
	0x8b, 0x92, 0x59, 0x2c, 0x0d, 0x41, 0x7a, 0x45, 0xf0, 0xe7, 0xa4, 0x77, 0xfe, 0x0f, 0x76, 0x1e,
	0xde, 0xb0, 0xa5, 0x93, 0xc5, 0x5c, 0x3e, 0x39, 0x9d, 0xe5, 0x93, 0xa3, 0xa0, 0xc8, 0x45, 0x28,
	0xb6, 0x86, 0x22, 0x97, 0xa0, 0xc8, 0x55, 0x50, 0x40, 0x43, 0x91, 0xab, 0xa0, 0xc8, 0x65, 0x28,
	0x5d, 0x0d, 0x45, 0xae, 0x80, 0x92, 0x87, 0x77, 0xb7, 0x34, 0x94, 0x2c, 0xa6, 0xf3, 0x21, 0xec,
	0x08, 0x8c, 0xc3, 0x12, 0x96, 0x6d, 0xf2, 0xd8, 0xd6, 0xda, 0x0c, 0xcc, 0x21, 0x3c, 0x50, 0xc9,
	0xa5, 0x38, 0xe4, 0x53, 0x8e, 0xb1, 0xcc, 0xbd, 0x77, 0xc8, 0xfb, 0xde, 0x25, 0xa2, 0x9f, 0xd9,
	0xb2, 0x35, 0x9f, 0xc3, 0x5e, 0x71, 0xf0, 0x03, 0xc9, 0x23, 0x0c, 0x04, 0x0e, 0x93, 0x38, 0x14,
	0xee, 0x2e, 0xad, 0x7a, 0x50, 0x98, 0xcf, 0x79, 0x84, 0x67, 0xda, 0xe8, 0x38, 0xd0, 0x14, 0x6c,
	0x22, 0xdd, 0x1e, 0x39, 0xd1, 0xb3, 0xf7, 0x87, 0x05, 0xdd, 0x33, 0x7e, 0x15, 0x63, 0xf8, 0x8e,
	0x92, 0xef, 0x28, 0xf9, 0x5f, 0xa0, 0xa4, 0xb3, 0x0f, 0xb6, 0xe0, 0x57, 0x31, 0x93, 0xb3, 0x14,
	0xdd, 0xbe, 0x7e, 0xcf, 0xe4, 0x0a, 0xef, 0x33, 0xe8, 0x29, 0xbe, 0x12, 0x5b, 0xb3, 0x9b, 0x7b,
	0x1f, 0xac, 0x44, 0xc9, 0x66, 0x2a, 0x6a, 0xe9, 0x29, 0xc2, 0xd7, 0x4a, 0xef, 0x18, 0xfa, 0xa5,
	0x15, 0xe6, 0x72, 0x1e, 0x40, 0x57, 0x14, 0xb4, 0x37, 0x0b, 0xb7, 0x06, 0xa5, 0xa3, 0xe0, 0x97,
	0x1d, 0xd4, 0xb6, 0x5f, 0x33, 0x31, 0xba, 0xc3, 0xb6, 0x1f, 0x41, 0xbf, 0xb4, 0xc2, 0x6c, 0xeb,
	0x40, 0x73, 0xc4, 0xc4, 0x88, 0x56, 0x6c, 0xf9, 0xf4, 0xec, 0xfd, 0x5e, 0x07, 0xe7, 0x38, 0x45,
	0x26, 0xb1, 0x12, 0x7d, 0x89, 0x78, 0xb5, 0x15, 0xc4, 0x1b, 0xc0, 0xbd, 0x0a, 0xd1, 0x2b, 0xc7,
	0xb2, 0x5f, 0x62, 0x7a, 0xe1, 0x2f, 0x57, 0xf8, 0x37, 0x4a, 0xec, 0xab, 0xf8, 0xaf, 0x3e, 0x48,
	0xcd, 0x35, 0x07, 0x69, 0x35, 0x57, 0xad, 0x35, 0x5c, 0xdd, 0xc0, 0x99, 0xd6, 0x06, 0xce, 0x78,
	0xa7, 0x70, 0xaf, 0x52, 0x2e, 0x53, 0x5a, 0xaf, 0xda, 0x8d, 0x6a, 0x2f, 0xb5, 0x29, 0x2f, 0x7f,
	0xbd, 0x54, 0xfe, 0x53, 0xd8, 0x7b, 0xc9, 0xe4, 0x70, 0x74, 0x9e, 0xb2, 0x58, 0xb0, 0xa1, 0xda,
	0xed, 0x16, 0x13, 0xc1, 0x1e, 0xb4, 0xe5, 0x3c, 0xc8, 0x83, 0xd9, 0x7e, 0x4b, 0xce, 0x55, 0xbb,
	0xbd, 0xdf, 0x6a, 0xe0, 0x2e, 0xc7, 0xbb, 0x79, 0x98, 0x59, 0x17, 0x50, 0xcd, 0x5d, 0x5c, 0x04,
	0x53, 0x8c, 0x43, 0x1e, 0x5f, 0x51, 0xa7, 0x3a, 0xbe, 0xcd, 0xc5, 0xb7, 0x5a, 0x61, 0xcc, 0x6f,
	0xd4, 0x8e, 0x18, 0x52, 0x67, 0xc8, 0xfc, 0x52, 0x2b, 0xe8, 0x42, 0x98, 0x07, 0x66, 0x0e, 0xb1,
	0x68, 0x0e, 0xe9, 0xc8, 0xb9, 0x9e, 0x57, 0xbc, 0x7f, 0xea, 0x60, 0xd1, 0xb4, 0xb5, 0x29, 0xb1,
	0x05, 0x0a, 0x48, 0x3e, 0x1c, 0x63, 0x6a, 0x72, 0x2c, 0x51, 0xe0, 0x9c, 0xf4, 0x8b, 0x14, 0x30,
	0xde, 0x8d, 0x45, 0x0a, 0x18, 0xef, 0x85, 0x57, 0x40, 0x69, 0xda, 0x2e, 0xbd, 0x02, 0x68, 0xbc,
	0x3c, 0x80, 0x9e, 0x4e, 0xb0, 0xe4, 0xa9, 0x89, 0xb5, 0x43, 0xfa, 0xc2, 0xb3, 0x3a, 0x28, 0xb7,
	0xf4, 0xa7, 0x4c, 0x75, 0x50, 0x16, 0x98, 0xbe, 0xc6, 0x94, 0x28, 0x47, 0xf7, 0x7d, 0xc3, 0x07,
	0xad, 0x52, 0x34, 0x53, 0x15, 0x25, 0xb6, 0xe8, 0x66, 0xe8, 0xeb, 0xde, 0x26, 0x0d, 0xf5, 0x23,
	0xe7, 0x99, 0xbd, 0x9e, 0x67, 0x7b, 0xd0, 0xbe, 0xe4, 0x93, 0x49, 0x20, 0xe7, 0xe6, 0x62, 0x6f,
	0x29, 0xf1, 0x7c, 0xee, 0xfd, 0xda, 0x00, 0xeb, 0x3c, 0x65, 0xe1, 0xc6, 0x8a, 0xd3, 0xfb, 0x28,
	0x1d, 0xa3, 0x0c, 0xcc, 0x60, 0x4b, 0xef, 0x23, 0xa5, 0x38, 0x09, 0x17, 0xb2, 0x6b, 0x2c, 0x66,
	0xf7, 0x14, 0x7a, 0xb2, 0x20, 0x9e, 0x76, 0xd2, 0x15, 0xdd, 0x2d, 0xe9, 0xc9, 0x75, 0xe9, 0x82,
	0xb1, 0x56, 0x5c, 0x30, 0xfb, 0x60, 0xab, 0x32, 0x09, 0xc9, 0xa2, 0xa9, 0x29, 0x66, 0xa1, 0x58,
	0xc3, 0x8d, 0xf6, 0x9d, 0xb8, 0xd1, 0x59, 0xc3, 0x8d, 0xd5, 0x57, 0x8f, 0x7d, 0xa7, 0xab, 0x07,
	0xd6, 0x5c, 0x3d, 0x79, 0x0f, 0xbb, 0x6b, 0x7b, 0xe8, 0xfd, 0x5c, 0x03, 0x4b, 0x7f, 0x18, 0x3d,
	0x84, 0x96, 0xc9, 0xb5, 0x66, 0x4e, 0xa6, 0xce, 0xd0, 0x81, 0x66, 0xcc, 0xa2, 0xec, 0x83, 0x98,
	0x9e, 0xd5, 0x87, 0x72, 0x88, 0x43, 0x1e, 0xb1, 0x49, 0xf6, 0xe9, 0x91, 0xcb, 0xaa, 0x75, 0x31,
	0xca, 0x37, 0x49, 0x3a, 0x56, 0x8d, 0x6d, 0x92, 0xd5, 0x36, 0x9a, 0x93, 0xd0, 0x71, 0xa1, 0x5d,
	0xed, 0x44, 0x26, 0x1e, 0xb5, 0x7e, 0x6c, 0x5e, 0xa5, 0xd3, 0xe1, 0x45, 0x8b, 0xfe, 0x56, 0x3c,
	0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x07, 0x12, 0x4f, 0xbc, 0x10, 0x00, 0x00,
}
