apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-book-manager
  labels:
    app: order-book-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-book-manager
  template:
    metadata:
      labels:
        app: order-book-manager
    spec:
      containers:
      - name: order-book-manager
        image: gcr.io/kosu-io/order-book-manager
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: order-book-manager
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: order-book-manager
