// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hw.proto

package hw

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	ChainId               uint64   `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ExchangeAddress       string   `protobuf:"bytes,2,opt,name=exchangeAddress,proto3" json:"exchangeAddress,omitempty"`
	MakerAddress          string   `protobuf:"bytes,3,opt,name=makerAddress,proto3" json:"makerAddress,omitempty"`
	MakerAssetData        string   `protobuf:"bytes,4,opt,name=makerAssetData,proto3" json:"makerAssetData,omitempty"`
	MakerFeeAssetData     string   `protobuf:"bytes,5,opt,name=makerFeeAssetData,proto3" json:"makerFeeAssetData,omitempty"`
	MakerAssetAmount      string   `protobuf:"bytes,6,opt,name=makerAssetAmount,proto3" json:"makerAssetAmount,omitempty"`
	MakerFee              string   `protobuf:"bytes,7,opt,name=makerFee,proto3" json:"makerFee,omitempty"`
	TakerAddress          string   `protobuf:"bytes,8,opt,name=takerAddress,proto3" json:"takerAddress,omitempty"`
	TakerAssetData        string   `protobuf:"bytes,9,opt,name=takerAssetData,proto3" json:"takerAssetData,omitempty"`
	TakerFeeAssetData     string   `protobuf:"bytes,10,opt,name=takerFeeAssetData,proto3" json:"takerFeeAssetData,omitempty"`
	TakerAssetAmount      string   `protobuf:"bytes,11,opt,name=takerAssetAmount,proto3" json:"takerAssetAmount,omitempty"`
	TakerFee              string   `protobuf:"bytes,12,opt,name=takerFee,proto3" json:"takerFee,omitempty"`
	SenderAddress         string   `protobuf:"bytes,13,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	FeeRecipientAddress   string   `protobuf:"bytes,14,opt,name=feeRecipientAddress,proto3" json:"feeRecipientAddress,omitempty"`
	ExpirationTimeSeconds string   `protobuf:"bytes,15,opt,name=expirationTimeSeconds,proto3" json:"expirationTimeSeconds,omitempty"`
	Salt                  string   `protobuf:"bytes,16,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Order) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *Order) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *Order) GetMakerAssetData() string {
	if m != nil {
		return m.MakerAssetData
	}
	return ""
}

func (m *Order) GetMakerFeeAssetData() string {
	if m != nil {
		return m.MakerFeeAssetData
	}
	return ""
}

func (m *Order) GetMakerAssetAmount() string {
	if m != nil {
		return m.MakerAssetAmount
	}
	return ""
}

func (m *Order) GetMakerFee() string {
	if m != nil {
		return m.MakerFee
	}
	return ""
}

func (m *Order) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *Order) GetTakerAssetData() string {
	if m != nil {
		return m.TakerAssetData
	}
	return ""
}

func (m *Order) GetTakerFeeAssetData() string {
	if m != nil {
		return m.TakerFeeAssetData
	}
	return ""
}

func (m *Order) GetTakerAssetAmount() string {
	if m != nil {
		return m.TakerAssetAmount
	}
	return ""
}

func (m *Order) GetTakerFee() string {
	if m != nil {
		return m.TakerFee
	}
	return ""
}

func (m *Order) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *Order) GetFeeRecipientAddress() string {
	if m != nil {
		return m.FeeRecipientAddress
	}
	return ""
}

func (m *Order) GetExpirationTimeSeconds() string {
	if m != nil {
		return m.ExpirationTimeSeconds
	}
	return ""
}

func (m *Order) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

type SignedOrder struct {
	ChainId               uint64   `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ExchangeAddress       string   `protobuf:"bytes,2,opt,name=exchangeAddress,proto3" json:"exchangeAddress,omitempty"`
	MakerAddress          string   `protobuf:"bytes,3,opt,name=makerAddress,proto3" json:"makerAddress,omitempty"`
	MakerAssetData        string   `protobuf:"bytes,4,opt,name=makerAssetData,proto3" json:"makerAssetData,omitempty"`
	MakerFeeAssetData     string   `protobuf:"bytes,5,opt,name=makerFeeAssetData,proto3" json:"makerFeeAssetData,omitempty"`
	MakerAssetAmount      string   `protobuf:"bytes,6,opt,name=makerAssetAmount,proto3" json:"makerAssetAmount,omitempty"`
	MakerFee              string   `protobuf:"bytes,7,opt,name=makerFee,proto3" json:"makerFee,omitempty"`
	TakerAddress          string   `protobuf:"bytes,8,opt,name=takerAddress,proto3" json:"takerAddress,omitempty"`
	TakerAssetData        string   `protobuf:"bytes,9,opt,name=takerAssetData,proto3" json:"takerAssetData,omitempty"`
	TakerFeeAssetData     string   `protobuf:"bytes,10,opt,name=takerFeeAssetData,proto3" json:"takerFeeAssetData,omitempty"`
	TakerAssetAmount      string   `protobuf:"bytes,11,opt,name=takerAssetAmount,proto3" json:"takerAssetAmount,omitempty"`
	TakerFee              string   `protobuf:"bytes,12,opt,name=takerFee,proto3" json:"takerFee,omitempty"`
	SenderAddress         string   `protobuf:"bytes,13,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	FeeRecipientAddress   string   `protobuf:"bytes,14,opt,name=feeRecipientAddress,proto3" json:"feeRecipientAddress,omitempty"`
	ExpirationTimeSeconds string   `protobuf:"bytes,15,opt,name=expirationTimeSeconds,proto3" json:"expirationTimeSeconds,omitempty"`
	Salt                  string   `protobuf:"bytes,16,opt,name=salt,proto3" json:"salt,omitempty"`
	Signature             string   `protobuf:"bytes,17,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SignedOrder) Reset()         { *m = SignedOrder{} }
func (m *SignedOrder) String() string { return proto.CompactTextString(m) }
func (*SignedOrder) ProtoMessage()    {}
func (*SignedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{1}
}

func (m *SignedOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedOrder.Unmarshal(m, b)
}
func (m *SignedOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedOrder.Marshal(b, m, deterministic)
}
func (m *SignedOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedOrder.Merge(m, src)
}
func (m *SignedOrder) XXX_Size() int {
	return xxx_messageInfo_SignedOrder.Size(m)
}
func (m *SignedOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SignedOrder proto.InternalMessageInfo

func (m *SignedOrder) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *SignedOrder) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *SignedOrder) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *SignedOrder) GetMakerAssetData() string {
	if m != nil {
		return m.MakerAssetData
	}
	return ""
}

func (m *SignedOrder) GetMakerFeeAssetData() string {
	if m != nil {
		return m.MakerFeeAssetData
	}
	return ""
}

func (m *SignedOrder) GetMakerAssetAmount() string {
	if m != nil {
		return m.MakerAssetAmount
	}
	return ""
}

func (m *SignedOrder) GetMakerFee() string {
	if m != nil {
		return m.MakerFee
	}
	return ""
}

func (m *SignedOrder) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *SignedOrder) GetTakerAssetData() string {
	if m != nil {
		return m.TakerAssetData
	}
	return ""
}

func (m *SignedOrder) GetTakerFeeAssetData() string {
	if m != nil {
		return m.TakerFeeAssetData
	}
	return ""
}

func (m *SignedOrder) GetTakerAssetAmount() string {
	if m != nil {
		return m.TakerAssetAmount
	}
	return ""
}

func (m *SignedOrder) GetTakerFee() string {
	if m != nil {
		return m.TakerFee
	}
	return ""
}

func (m *SignedOrder) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *SignedOrder) GetFeeRecipientAddress() string {
	if m != nil {
		return m.FeeRecipientAddress
	}
	return ""
}

func (m *SignedOrder) GetExpirationTimeSeconds() string {
	if m != nil {
		return m.ExpirationTimeSeconds
	}
	return ""
}

func (m *SignedOrder) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *SignedOrder) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type SignOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOrderRequest) Reset()         { *m = SignOrderRequest{} }
func (m *SignOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SignOrderRequest) ProtoMessage()    {}
func (*SignOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{2}
}

func (m *SignOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOrderRequest.Unmarshal(m, b)
}
func (m *SignOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOrderRequest.Marshal(b, m, deterministic)
}
func (m *SignOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOrderRequest.Merge(m, src)
}
func (m *SignOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SignOrderRequest.Size(m)
}
func (m *SignOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOrderRequest proto.InternalMessageInfo

func (m *SignOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type SignOrderResponse struct {
	SignedOrder          *SignedOrder `protobuf:"bytes,1,opt,name=signedOrder,proto3" json:"signedOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignOrderResponse) Reset()         { *m = SignOrderResponse{} }
func (m *SignOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SignOrderResponse) ProtoMessage()    {}
func (*SignOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{3}
}

func (m *SignOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOrderResponse.Unmarshal(m, b)
}
func (m *SignOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOrderResponse.Marshal(b, m, deterministic)
}
func (m *SignOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOrderResponse.Merge(m, src)
}
func (m *SignOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SignOrderResponse.Size(m)
}
func (m *SignOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOrderResponse proto.InternalMessageInfo

func (m *SignOrderResponse) GetSignedOrder() *SignedOrder {
	if m != nil {
		return m.SignedOrder
	}
	return nil
}

type HashOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashOrderRequest) Reset()         { *m = HashOrderRequest{} }
func (m *HashOrderRequest) String() string { return proto.CompactTextString(m) }
func (*HashOrderRequest) ProtoMessage()    {}
func (*HashOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{4}
}

func (m *HashOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashOrderRequest.Unmarshal(m, b)
}
func (m *HashOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashOrderRequest.Marshal(b, m, deterministic)
}
func (m *HashOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashOrderRequest.Merge(m, src)
}
func (m *HashOrderRequest) XXX_Size() int {
	return xxx_messageInfo_HashOrderRequest.Size(m)
}
func (m *HashOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashOrderRequest proto.InternalMessageInfo

func (m *HashOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type HashOrderResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashOrderResponse) Reset()         { *m = HashOrderResponse{} }
func (m *HashOrderResponse) String() string { return proto.CompactTextString(m) }
func (*HashOrderResponse) ProtoMessage()    {}
func (*HashOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{5}
}

func (m *HashOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashOrderResponse.Unmarshal(m, b)
}
func (m *HashOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashOrderResponse.Marshal(b, m, deterministic)
}
func (m *HashOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashOrderResponse.Merge(m, src)
}
func (m *HashOrderResponse) XXX_Size() int {
	return xxx_messageInfo_HashOrderResponse.Size(m)
}
func (m *HashOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashOrderResponse proto.InternalMessageInfo

func (m *HashOrderResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type CreateOrderRequest struct {
	TakerAddress          string   `protobuf:"bytes,1,opt,name=takerAddress,proto3" json:"takerAddress,omitempty"`
	MakerAssetAddress     string   `protobuf:"bytes,2,opt,name=makerAssetAddress,proto3" json:"makerAssetAddress,omitempty"`
	TakerAssetAddress     string   `protobuf:"bytes,3,opt,name=takerAssetAddress,proto3" json:"takerAssetAddress,omitempty"`
	MakerAssetAmount      string   `protobuf:"bytes,4,opt,name=makerAssetAmount,proto3" json:"makerAssetAmount,omitempty"`
	TakerAssetAmount      string   `protobuf:"bytes,5,opt,name=takerAssetAmount,proto3" json:"takerAssetAmount,omitempty"`
	ExpirationTimeSeconds string   `protobuf:"bytes,6,opt,name=expirationTimeSeconds,proto3" json:"expirationTimeSeconds,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{6}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *CreateOrderRequest) GetMakerAssetAddress() string {
	if m != nil {
		return m.MakerAssetAddress
	}
	return ""
}

func (m *CreateOrderRequest) GetTakerAssetAddress() string {
	if m != nil {
		return m.TakerAssetAddress
	}
	return ""
}

func (m *CreateOrderRequest) GetMakerAssetAmount() string {
	if m != nil {
		return m.MakerAssetAmount
	}
	return ""
}

func (m *CreateOrderRequest) GetTakerAssetAmount() string {
	if m != nil {
		return m.TakerAssetAmount
	}
	return ""
}

func (m *CreateOrderRequest) GetExpirationTimeSeconds() string {
	if m != nil {
		return m.ExpirationTimeSeconds
	}
	return ""
}

type CreateOrderResponse struct {
	Order                *SignedOrder `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f22fcc6a44138406, []int{7}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrder() *SignedOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*SignedOrder)(nil), "SignedOrder")
	proto.RegisterType((*SignOrderRequest)(nil), "SignOrderRequest")
	proto.RegisterType((*SignOrderResponse)(nil), "SignOrderResponse")
	proto.RegisterType((*HashOrderRequest)(nil), "HashOrderRequest")
	proto.RegisterType((*HashOrderResponse)(nil), "HashOrderResponse")
	proto.RegisterType((*CreateOrderRequest)(nil), "CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "CreateOrderResponse")
}

func init() { proto.RegisterFile("hw.proto", fileDescriptor_f22fcc6a44138406) }

var fileDescriptor_f22fcc6a44138406 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x95, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x95, 0xd6, 0x49, 0xe3, 0x49, 0xda, 0xc6, 0x13, 0x90, 0x56, 0x11, 0x87, 0xca, 0x42,
	0x10, 0x21, 0xb4, 0xaa, 0x02, 0x07, 0x38, 0x56, 0x45, 0xa8, 0x9c, 0x90, 0x5c, 0x24, 0xce, 0x4b,
	0x3c, 0xc4, 0x16, 0xc9, 0x3a, 0x78, 0x37, 0xa2, 0x2f, 0xc2, 0x0b, 0x70, 0xe7, 0xe1, 0x78, 0x03,
	0x94, 0xdd, 0x38, 0xf6, 0xda, 0x0e, 0x12, 0x97, 0x9e, 0x7a, 0xf3, 0xcc, 0xfc, 0xb3, 0x9b, 0x7f,
	0xe7, 0x1b, 0x05, 0xfa, 0xc9, 0x0f, 0xbe, 0xce, 0x33, 0x9d, 0x85, 0x7f, 0x3c, 0xe8, 0x7e, 0xcc,
	0x63, 0xca, 0x91, 0xc1, 0xc9, 0x3c, 0x11, 0xa9, 0xfc, 0x10, 0xb3, 0xce, 0x45, 0x67, 0xea, 0x45,
	0x45, 0x88, 0x53, 0x38, 0xa7, 0xbb, 0x79, 0x22, 0xe4, 0x82, 0xae, 0xe2, 0x38, 0x27, 0xa5, 0xd8,
	0xd1, 0x45, 0x67, 0xea, 0x47, 0xf5, 0x34, 0x86, 0x30, 0x5c, 0x89, 0x6f, 0x94, 0x17, 0xb2, 0x63,
	0x23, 0x73, 0x72, 0xf8, 0x0c, 0xce, 0x6c, 0xac, 0x14, 0xe9, 0x77, 0x42, 0x0b, 0xe6, 0x19, 0x55,
	0x2d, 0x8b, 0x2f, 0x21, 0x30, 0x99, 0xf7, 0x44, 0xa5, 0xb4, 0x6b, 0xa4, 0xcd, 0x02, 0xbe, 0x80,
	0x51, 0xd9, 0x7f, 0xb5, 0xca, 0x36, 0x52, 0xb3, 0x9e, 0x11, 0x37, 0xf2, 0x38, 0x81, 0x7e, 0x71,
	0x00, 0x3b, 0x31, 0x9a, 0x7d, 0xbc, 0x75, 0xa0, 0xab, 0x0e, 0xfa, 0xd6, 0x81, 0xae, 0x39, 0xd0,
	0xae, 0x03, 0xdf, 0x3a, 0xd0, 0x0d, 0x07, 0xba, 0xe1, 0x00, 0xac, 0x03, 0xdd, 0xe6, 0x40, 0xd7,
	0x1d, 0x0c, 0xac, 0x03, 0xdd, 0xe2, 0xa0, 0x38, 0x80, 0x0d, 0xad, 0x83, 0x22, 0xc6, 0xa7, 0x70,
	0xaa, 0x48, 0xc6, 0xa5, 0x85, 0x53, 0x23, 0x70, 0x93, 0x78, 0x09, 0xe3, 0xaf, 0x44, 0x11, 0xcd,
	0xd3, 0x75, 0x4a, 0x52, 0x17, 0xda, 0x33, 0xa3, 0x6d, 0x2b, 0xe1, 0x6b, 0x78, 0x4c, 0x77, 0xeb,
	0x34, 0x17, 0x3a, 0xcd, 0xe4, 0xa7, 0x74, 0x45, 0xb7, 0x34, 0xcf, 0x64, 0xac, 0xd8, 0xb9, 0xe9,
	0x69, 0x2f, 0x22, 0x82, 0xa7, 0xc4, 0x52, 0xb3, 0x91, 0x11, 0x99, 0xef, 0xf0, 0x67, 0x17, 0x06,
	0xb7, 0xe9, 0x42, 0x52, 0xfc, 0x40, 0xde, 0x03, 0x79, 0xf7, 0x48, 0x1e, 0x3e, 0x01, 0x5f, 0xa5,
	0x0b, 0x29, 0xf4, 0x26, 0x27, 0x16, 0x98, 0x42, 0x99, 0x08, 0x2f, 0x61, 0xb4, 0xc5, 0xd2, 0x40,
	0x19, 0xd1, 0xf7, 0x0d, 0xa9, 0x6d, 0x47, 0x37, 0xdb, 0xc6, 0x86, 0xcc, 0xc1, 0xac, 0xc7, 0x6d,
	0xd5, 0x26, 0xc3, 0x6b, 0x08, 0x2a, 0x1d, 0x6a, 0x9d, 0x49, 0x45, 0xc8, 0x61, 0xa0, 0x4a, 0xba,
	0x77, 0x8d, 0x43, 0x5e, 0x21, 0x3e, 0xaa, 0x0a, 0xb6, 0xd7, 0xde, 0x08, 0x95, 0xfc, 0xc7, 0xb5,
	0xcf, 0x21, 0xa8, 0x74, 0xec, 0xae, 0x45, 0xf0, 0x12, 0xa1, 0x12, 0xd3, 0x31, 0x8c, 0xcc, 0x77,
	0xf8, 0xeb, 0x08, 0xf0, 0x3a, 0x27, 0xa1, 0xc9, 0x39, 0xbd, 0x8e, 0x5a, 0xa7, 0x05, 0xb5, 0x62,
	0x09, 0xec, 0xf0, 0x9d, 0xe5, 0x6b, 0x16, 0xf6, 0xc0, 0x39, 0xea, 0xe3, 0x0a, 0x70, 0x8e, 0xba,
	0x6d, 0x65, 0xbc, 0x03, 0x2b, 0xd3, 0x06, 0x67, 0xf7, 0x00, 0x9c, 0x07, 0x41, 0xe9, 0xfd, 0x03,
	0x94, 0xf0, 0x2d, 0x8c, 0x9d, 0x37, 0xda, 0xbd, 0x67, 0xe8, 0x8e, 0xc0, 0x1d, 0xa0, 0x2d, 0xcd,
	0x7e, 0x77, 0xc0, 0xbf, 0xc9, 0xf4, 0x67, 0xb1, 0x5c, 0x92, 0xc6, 0x19, 0xf8, 0x7b, 0x1a, 0x30,
	0xe0, 0x75, 0x96, 0x26, 0xc8, 0x9b, 0xb0, 0xcc, 0xc0, 0xdf, 0x8f, 0x12, 0x03, 0x5e, 0x07, 0x61,
	0x82, 0xbc, 0x39, 0xe9, 0x37, 0x30, 0xa8, 0xfc, 0x60, 0x1c, 0xf3, 0xe6, 0x88, 0x27, 0x8f, 0x78,
	0x8b, 0xa7, 0x2f, 0x3d, 0xf3, 0xa7, 0xff, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0xe1,
	0x04, 0x0a, 0x00, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HotWalletClient is the client API for HotWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HotWalletClient interface {
	SignOrder(ctx context.Context, in *SignOrderRequest, opts ...grpc.CallOption) (*SignOrderResponse, error)
	HashOrder(ctx context.Context, in *HashOrderRequest, opts ...grpc.CallOption) (*HashOrderResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type hotWalletClient struct {
	cc *grpc.ClientConn
}

func NewHotWalletClient(cc *grpc.ClientConn) HotWalletClient {
	return &hotWalletClient{cc}
}

func (c *hotWalletClient) SignOrder(ctx context.Context, in *SignOrderRequest, opts ...grpc.CallOption) (*SignOrderResponse, error) {
	out := new(SignOrderResponse)
	err := c.cc.Invoke(ctx, "/HotWallet/SignOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotWalletClient) HashOrder(ctx context.Context, in *HashOrderRequest, opts ...grpc.CallOption) (*HashOrderResponse, error) {
	out := new(HashOrderResponse)
	err := c.cc.Invoke(ctx, "/HotWallet/HashOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotWalletClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/HotWallet/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotWalletServer is the server API for HotWallet service.
type HotWalletServer interface {
	SignOrder(context.Context, *SignOrderRequest) (*SignOrderResponse, error)
	HashOrder(context.Context, *HashOrderRequest) (*HashOrderResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}

func RegisterHotWalletServer(s *grpc.Server, srv HotWalletServer) {
	s.RegisterService(&_HotWallet_serviceDesc, srv)
}

func _HotWallet_SignOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotWalletServer).SignOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotWallet/SignOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotWalletServer).SignOrder(ctx, req.(*SignOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotWallet_HashOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotWalletServer).HashOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotWallet/HashOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotWalletServer).HashOrder(ctx, req.(*HashOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotWallet_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotWalletServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HotWallet/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotWalletServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HotWallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HotWallet",
	HandlerType: (*HotWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignOrder",
			Handler:    _HotWallet_SignOrder_Handler,
		},
		{
			MethodName: "HashOrder",
			Handler:    _HotWallet_HashOrder_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _HotWallet_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hw.proto",
}
